Update pom.xml
need to update 

error: Source option 6 is no longer supported. Use 7 or later.
[[1;31mERROR[m] error: Target option 6 is no longer supported. Use 7 or later.